# Generated by Django 2.2.16 on 2021-01-18 11:50

import asterix.apps.account.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210114_0723'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', asterix.apps.account.managers.UserManager()),
            ],
        ),
    ]
