# Generated by Django 2.2.16 on 2021-01-20 03:24

from django.db import migrations

from django.contrib.gis.utils import LayerMapping
from ..models import County
from django.db import migrations

# Won't run, no corresponding database created yet, ignore
class Migration(migrations.Migration):

    dependencies = [("shapefiles", "0003_county_dis")]

    operations = []
