# Generated by Django 2.2.16 on 2021-01-20 03:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0004_load_kenya_river'),
    ]

    operations = [
        migrations.CreateModel(
            name='KenyaRiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnode_field', models.BigIntegerField()),
                ('tnode_field', models.BigIntegerField()),
                ('lpoly_field', models.BigIntegerField()),
                ('rpoly_field', models.BigIntegerField()),
                ('length', models.FloatField()),
                ('klrivers_field', models.BigIntegerField()),
                ('klrivers_i', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Kenya rivers',
            },
        ),
        migrations.CreateModel(
            name='KenyaRoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnode_field', models.BigIntegerField()),
                ('tnode_field', models.BigIntegerField()),
                ('lpoly_field', models.BigIntegerField()),
                ('rpoly_field', models.BigIntegerField()),
                ('length', models.FloatField()),
                ('kenroad_field', models.BigIntegerField()),
                ('kenroad_id', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'kenya roads',
            },
        ),
    ]
