# Generated by Django 2.2.16 on 2021-01-20 19:42

from django.db import migrations
from .. import loader


def load_data(apps, shema_editor):
    loader.run()


class Migration(migrations.Migration):

    dependencies = [("shapefiles", "0007_load_rivers")]

    operations = [migrations.RunPython(load_data)]
