# Generated by Django 2.2.16 on 2021-01-14 08:45

import os
from django.contrib.gis.utils import LayerMapping
from asterix.apps.shapefiles.models import KenyaRoad

DATA_DIR_NAME = os.path.join('data', 'kenya_roads' )

# Auto-generated `LayerMapping` dictionary for KenyaRoad model
kenyaroad_mapping = {
    'fnode_field': 'FNODE_',
    'tnode_field': 'TNODE_',
    'lpoly_field': 'LPOLY_',
    'rpoly_field': 'RPOLY_',
    'length': 'LENGTH',
    'kenroad_field': 'KENROAD_',
    'kenroad_id': 'KENROAD_ID',
    'geom': 'MULTILINESTRING',
}


river_shp = os.path.abspath(
    os.path.join(os.path.dirname(__file__), DATA_DIR_NAME, 'kenya_roads.shp'), )


def run(verbose=True):
    """
    This function used the LayerMapping import utility to
    load a shapefile to the database
    """
    # Takes model name, path to shapefile, mapping dict, encoding format
    lm = LayerMapping(KenyaRoad,
                      river_shp,
                      kenyaroad_mapping,
                      transform=False,
                      encoding='iso-8859-1')
    lm.save(strict=True, verbose=verbose)
