# Generated by Django 2.2.16 on 2021-01-14 07:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marker',
            options={'verbose_name_plural': 'markers'},
        ),
        migrations.AlterField(
            model_name='marker',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
