# Generated by Django 2.2.16 on 2021-01-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_auto_20210114_0749'),
    ]

    operations = [
    ]
