# Generated by Django 2.2.16 on 2021-01-14 08:45

import os
from django.contrib.gis.utils import LayerMapping
from ..models import County
from django.db import migrations

county_mapping = {
    'counties': 'Counties',
    'codes': 'Codes',
    'cty_code': 'Cty_CODE',
    'dis': 'dis',
    'geom': 'MULTIPOLYGON',
}

county_shp = os.path.abspath(
    os.path.join(os.path.dirname(__file__), 'data', 'counties.shp'), )


def run(verbose=True):
    lm = LayerMapping(County,
                      county_shp,
                      county_mapping,
                      transform=False,
                      encoding='iso-8859-1')
    lm.save(strict=True, verbose=verbose)


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_auto_20210114_0749'),
    ]

    operations = [migrations.RunPython(run)]
