# Generated by Django 2.2.16 on 2021-01-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0004_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='code',
            new_name='codes',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='name',
            new_name='counties',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='city_code',
            new_name='cty_code',
        ),
    ]
