# Generated by Django 2.2.16 on 2021-01-19 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_auto_20210119_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
