# Generated by Django 2.2.16 on 2021-01-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0007_remove_county_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='County',
        ),
    ]
